---
title: 'Basic R'
author: Ben Harden
date: '2021-05-05'
level: 2
slug: []
categories: []
tags: []
draft: no
quiz: https://rstudio.cloud/spaces/170089/project/2870342
---

Now that we know a little about R and why we might want to use it, it's time to learn some of the basics. 

## R Familiarization

If you've never used R or RStudio before it's worth a little bit of orientation. Follow the following steps to begin your familiarization:

### 1. Basic R

You can get some information on how to use R from [this tutorial](https://rstudio.cloud/learn/primers/1.2). Watch the videos and run the interactive code chunks to learn some of the basics.

### 2. RStudio Interface

Watch this video to orient yourself to the RStudio Interface. RStudio is a user friendly application that makes running R code a little easier. It is the interface you will be using on the RStudio Cloud.

<iframe width="100%" height = "500" src="https://www.youtube.com/embed/cnQ-v1UUWyE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 3. Scripting

The final part of the video above talks about scripting. I like to think of scripts as a little like recipes. You lay out the ingredients and logical steps someone (or future you!) would need to follow in order to get a particular, reproducible outcome. In this case, it's R that is going to follow your script to do a particular analysis or make a plot. Although a cake would be nice.

Writing commands in the console is a little like cooking on the fly with whatever you have to hand. Sometimes that's the right way to make a meal (or play with data). Most times though, you're going to want to make a script to record what you've done.

Below is a quick video intro to making a script.

<iframe title="vimeo-player" src="https://player.vimeo.com/video/557632079" width="800" height="600" frameborder="0" allowfullscreen></iframe>

## Exercise

Follow the link below which will take you to a project in RStudio Cloud. In that project, you should open (double-click) `instructions.txt` in the files window (bottom right) and follow the instructions.

<!-- 1. Open a new script file and name it "test_script.R" -->
<!-- 1. Use this script to record the steps you would take to do the following: -->
<!--   1. Make a new object which is a vector of the numbers 1, 3, 5, 8, 11, 20 -->
<!--   1. Extract the 3rd value in this vector -->
<!--   1. Find the mean and range of this vector -->
<!--   1. Make a new object with is your original object multiplied by 10 -->
<!-- 1. Comment your lines of code so you know what each line does -->

Once you've finished, click the "Exit Ticket" button to inform me that you've completed the level and need feedback.

## Practice Discussion

Throughout this course we are going to have [small-group discussion](/discussions). To get the feel for these we are going to have a practice discussion based on some of the introduction presented here.

In the group discussions, you should be prepared to talk about the following:

- What previous experience have you had working with data? What have been challenges you've faced?
- To what degree is reproducibility important in science? What did you read about R that seems like it will be a useful tool in this regard?

This discussion will not be scored - it is an opportunity for you to get familiar with the format. However, this is an important discussion none-the-less so come prepared.
