baseURL: /
languageCode: en-us
title: S301
theme: hugo-ink
paginate: 5
copyright: © Sea Education Association 2021
pygmentsstyle: vs
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
googleAnalytics: UA-123-45
disqusShortname: ink-demo
params:
  avatar: /images/SEA_logo-print-sm_website.jpg
  disableDisqusTypes: page
  featherIconsCDN: yes
  mode: auto
  social:
    - icon: calendar
      name: Shore Calendar
      url: https://docs.google.com/spreadsheets/d/1GA_RiwgtjIrk25PEriOEbmUGusqs1zdNmdw7apRk2Mo/edit?usp=sharing
    - icon: book-open
      name: Google Classroom
      url: https://classroom.google.com
    - icon: cloud
      name: RStudio Cloud
      url: https://rstudio.cloud/spaces/170089/
  subtitle: Data Communication and Visualization
  customCSS: css/mycustom.css
menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Classes
      url: /classes
      weight: 2
    - name: Discussions
      url: /discussions
      weight: 4
    - name: Syllabus
      url: /docs/S301_DCV_syllabus.pdf
      weight: 5
taxonomies:
  tag: tags
