---
title: "Overview and Plan"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 1
slug: []
categories: []
tags: []
draft: no
---

Your communication project will be a single person narrated radio story about some element of oceans and their relationship to climate change. It will end up being about 2-3 minutes long and should seek to incorporate many elements of our discussions around writing for voice, communicating about the climate and storytelling.

Your first step is to decide on what story you are going to tell. We'll have some in-class discussions to help this process, but you should also spend a little time searching on the internet or in the SEA library for inspiration. Your story can be about anything so long as it relates to oceans and climate. 

Once you have some proto-ideas, you should fill out [this worksheet](comms_planning_sheet.pdf) to expand your ideas and think about how specifically you want to tell the story. You should list a few ideas as a starting point and list some pros and cons. Once you've settled on an idea, you will need to explain:

* What you story will be about?
* Who is the main character and what do they want?
* What happens at the beginning, middle and end?
* What kind of story will this be?
* How you hope this story will leave people feeling?

Once you've completed this form, you can hand it to me and I'll give some feedback before we both agree on a course of action.

Then fill out an exit ticket and move on to drafting your story!