---
title: 'Climate Stories'
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 2
slug: []
categories: []
tags: []
draft: no
---

Let's apply some of this understanding to stories about the environment and climate change.

## Reading

You will be assigned in groups to one of the following stories

### Story 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/nNcX8j3gJDw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 2

<iframe width="560" height="315" src="https://www.youtube.com/embed/FX7rk9PWZWE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 3

<iframe width="560" height="315" src="https://www.youtube.com/embed/nYlnoxgqEWo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Story 4

<iframe width="560" height="315" src="https://www.youtube.com/embed/iXt0rQNlhuM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Excercise

You should watch/listen to you assigned story a few times and take notes on the following:

* What is key climate topic is being addressed?
* What type of story is this story? Is the story wrapped up by the end of the piece?
* Who are the characters who are taking action? What are they doing?
* What elements of effective communication that we explored in the previous module are on display here? What is less effective about the mode of delivery?
* How could you tell this story differently?

In class, you will meet with your peers assigned the same story and gather your ideas together to present to the group.

Fill in an exit ticket when you are done.


