---
title: "Effective Poster Design"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

You've now made some initial plots and thought about your role in the team. We are one week away from presenting results so the work of the next few days is to refine the story you've begun to uncover in your data and think about how you want to present that.

# Reading 

Making an effective research poster is not easy, especially for a scientist without any graphic design training. To prepare for the making and presenting of your research posters, we are going to discuss some best practices in graphic design.

To be able to discuss poster design with some theory in mind, I'd like you to read the following resources which talk about graphic design principals:

<https://www.presentationzen.com/chapter6_spread.pdf>

<https://saylordotorg.github.io/text_business-information-systems-design-an-app-for-that/s07-professionalism-in-deliverable.html>

<https://blog.usejournal.com/10-basic-principles-of-graphic-design-b74be0dbdb58>

Please take some notes as you read on points that speak to effective poster design.

Reflect on what was new to you in this in an exit ticket (no Test Your Understanding).