---
title: "Project Options"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 1
slug: []
categories: []
tags: []
draft: no
---

Our goal of this project is to create at least one visualization that seeks to tell a story about the cruise region relevant to your oceanography project.

You're going to have a [few options](/datasets/) for data to work with and you should work with me to make sure that you are setting yourself a challenge suitable for your experience level at this point in the class. That's what this level is about - making a manageable plan.

<!-- You should look through the [possible data sets](/datasets/), talk with your peers and me and think about what kind of data would be most relevant to your project and present the appropriate level of challenge. If you have other ideas not covered in the page above them come speak to me ASAP. -->

## What can your viz be?

So, what can you make? Well, it's kinda up to you. You'll work with me to ensure that your visualization is both relevant to your oceanography project and setting you the appropriate level of challenge.

In general, you should think about your visualization as something that would be useful in your research proposal and/or research poster. For example, your visualization could be a presentation of:

* Previous cruise data that will let you frame your research questions and expectations.

* Other cruise data (WOCE?) that you are using to equally frame your questions

* External data (satellite, ARGO, etc.) shown on a map

* Some statistical representation of how certain variables co-vary

* A proposed sampling plan showing sampling locations/regions

* Some combination of all the above

Multi-paneled visualizations are in bounds here - especially if you need, for example, a map to contextualize other data collected subsurface.

## What you need to do

You'll get [this worksheet](vis_planning_sheet.pdf) in class. And I will ask you to fill it in with the following:

* What is your project topic? (can still be a little broad)

* A reflection on your current comfort level with the R work and your impression of which of the follow categories you fit into:
  * Emerging: Never done this before and it's presented a decent challenge
  * Proficient: Feel OK - challenge has been fine. Happy to apply skills presented.
  * Advancing: Looking for the next level of challenge

* Take a look through the [data sources I have gathered](/datasets/) and make a list of which would be appropriate to your topic and why.

* Take some time to think about what kind of visualization you might conceive of making at this point. I'd like you to sketch out two possible designs based on two different data sets you wrote down for the previous section. Take some time to consider:
  * what needs to go on what axis
  * what kinds of geoms you might use
  * whether you need a color scale
  * what parts of the visualization as you have it do you feel like you have a good handle on and which you dont.
  * whether you will need to go and collect additional data
  * pick which one you are initially going to pursue.
  
To complete this level, you should hand this sheet to me and we can chat about your plan. We will come to an agreement about the appropriateness of the plan and you can then move on to level 2 (once you've filled in an exit ticket).
