---
title: "Writing for Voice"
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 1
slug: []
categories: []
tags: []
draft: no
---

In this module we're going to look at strategies for effective communication on the radio and apply this to thinking about how best to tell stories about different kinds of science including climate change.

For this level, we're going to be covering the ideas in class. I'm going to link to the stories we will (or have) listened to and some key takeaways. You still need to fill out an exit ticket so you can reflect on what you have learned.

## Stories

### Flag Design

This story is an [early episode](https://99percentinvisible.org/episode/episode-06-99-symbolic/) of Roman Mars' [99% Invisible](https://99percentinvisible.org/) podcast. It's fast-paced and intricately cut together and demonstrates some key features of grabbing people's attention and making clear descriptions of things the audience can't see.

<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/17733995&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>

### How Many Trees?

A pretty straight [science radio story from NPR](https://www.npr.org/sections/goatsandsoda/2015/09/02/436919052/tree-counter-is-astonished-by-how-many-trees-there-are) which shows us some things about working with numbers and laying out a science mystery story.

<iframe src="https://www.npr.org/player/embed/436919052/436966850" width="100%" height="290" frameborder="0" scrolling="no" title="NPR embedded audio player"></iframe>

### Glowing Orbs

Nate DiMeo has a podcast call [The Memory Palace](https://thememorypalace.us) which is short stories told artfully about history. In [this episode](https://thememorypalace.us/the-glowing-orbs/) he talks about John Glenn's mission to space and the mystery he found along the way. It is slow-paced, poetic and demonstrates a different kind of vocal performance to the stories above.

<audio controls>
  <source src="Episode61_GlowingOrbs_edited.mp3" type="audio/mp3">
</audio>

## Writing for Voice

Remember, good writing is good writing regardless of the format. There's more similar than different between writing for radio and writing for other mediums. That said, here are some tips for effective radio writing.

* **Write like you speak**: to make it personal and intimate, you have to sound like a real person using real words and expressions that people use in everyday life. One way to do this when writing a radio piece is just to talk about your topic to a friend and record what you say (including the bits where they ask you to explain what you mean when you use complicated language). You canthen transcribe that and use it as a basis for the kinds of language and sentence structure they might use for your story. Its not about mimicking your natural tenancies exactly, its more about using these to design this “best version” of you for radio.

* **Use short sentences**: run-ons, big clauses, subject a long way from the start of the sentence - all of these things make listening to someone difficult. Keep it to one idea per sentence. In the end, this is not bad advice for writing more generally anyway.

* **Use concise, vivid imagery**: You can't use pictures so use the audiences imagination to generate scene and a sense of place. Tap into common imagery and use the diversity of peoples imaginations to your advantage.

* **Write in a logical simple order**: The listener can't go back and reread what you wrote so if they get confused along the way then they'll stay that way.

* **Grab their attention**: You wont always have everyone's full attention – listeners are often driving, doing the dishes, having a conversation etc. You have to grab peoples’ attention and then sustain it by laying out a story in an entertaining and logical manner. Sign-posting can also be effective.

* **Make it personal**: Radio is like having someone talking directly to you. Remember to write like you are talking to just one person and not an audience-filled room.
