---
title: 'Synthesize Your Understanding'
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 4
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/MzQ0NzAxMjMwNDU0/a/NDAyMTA2NjQwNjA5/details
---

To synthesize what you have learned so far, I'd like you to complete **one** of the exercises below:

## 1. Write a compelling Explainer

"Explainers" are radio/video segments that will give an overview of a topic/subject. They are typically short and will focus on moving people quickly through the what, how, whys of the topic at hand. Think: "How do people make pencils?" or "Plant anatomy in 60 seconds".

I'd like you to use what you've learned in this module and write a short Explainer for something you've been learning about in oceanography class. This should be for a general public audience.

You should:

* Pick a concept/topic in oceanography that you think is interesting and would want to tell others about.
* Think of a specific family member/friend who you think might be interested in it, but who wont already be familiar.
* Write a 200-300 word script intended to be spoken that describes the process to your chosen audience whilst upholding good practices in radio writing and strategies for communicating science/climate.
* Submit on the Google Classroom link below.

## 2. Annotate a Script

I'd like you to demonstrate what you understand about effective radio writing and science communication by annotating a real radio script. 

You should:

* Go find yourself a short radio script (probably around 4-5 min story). If you are struggling to find one, head over to NPR and almost all their stories are there with the transcript of the story.
* Print out the script on paper
* Annotate the script by hand with key pointers about what the narrator is doing in their writing. Don't focus on what the interviewee is saying quite so much unless you think they are also being effective/ineffective communicators.
* Note the effective strategies and also the ineffective ones. For the ineffective strategies, you should offer a potential alternative method.
* Make at least 10 annotations on the script highlighting a range of strategies we've discussed.

You can hand this annotated script directly to me and I'll review it and give you feedback.