---
title: "Getting Started"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/MzM4MTMyMTU4Mjgy/m/MzQ5ODM1NjA0NDAw/details
quiz_text: "Go to Google Classroom"
---

For our data exploration and visualization work, we are going to use a programming language called R. R is a very popular tool for working with data in sciences and is a one-stop-shop for data input, organization, graphics and web presentations. In fact this whole website was built within R. There is a lot to it and it can feel overwhelming at first so hold tight if you've never done any of this kind of work before.

## What is R and why use it?

R is a programming language. That means it's a piece of computer software that can interpret written commands and execute them in sequence to do a specific task such as, in our case, read in data, manipulate it, and create/edit a figure. There are many many programming languages out there, most with a specific goal in mind. HTML, which makes websites, is one example. You may have heard of or used others such as python, MATLAB, java, fortran...

A tool that can achieve similar goals to R is Microsoft Excel. Most of you have probably worked in Excel to look at and plot data. Excel is a very visual way to work with data and make plots, and is pretty easy to learn, but this usability comes at a price:

* In Excel, the interface is point-and-click meaning you select data using your mouse and then select actions from a toolbar. This can be really easy to learn, but is limited because it's hard to record what you have done to your data or indeed do exactly the same thing again another time. R allows you to write scripts which automates this process and makes it reproducible.

* In Excel, you work on a sheet and manipulate the data directly. This can result in you accidentally removing data, editing it without being able to undo, or otherwise create a mess wherein the original data becomes a new version with no documentation or ability for someone else to reproduce what you've done. 

* Excel is also not free so we limit our ability to collaborate and interact with the world by keeping the analysis behind a paywall. This has changed a little with the advent of Google Sheets, but the compatibility is still not perfect.

Although there is also can be a steep learning curve with R, Dr. Rob Schlegel (from the Woods Hole Oceanographic Institution) sums up nicely why using R is a good idea for data science as part of his R workshop. Please read [section 1.3 of his guide](https://robwschlegel.github.io/Intro_R_Workshop/prelim.html#why-use-r).

## Setting up R

Most people combine the language R with a user interface called RStudio - this is a point-and-click program that takes the simplicity and user-friendly nature of those features to make the coding part easier.

You can download RStudio on your computer, but for this course we're going to use RStudio Cloud, an online version of RStudio that will allow me to more easily see your work and help you move forward.

You will need to register for a free RStudio Cloud account by visiting the [RStudio Cloud site](https://rstudio.cloud/plans/free) and clicking on "sign up now".

Once you've created your account, click below to go to the Google Classroom and click the link there to be added to my RStudio Cloud Classroom. You can move on to [level 2](../level-2/) once you've been added to the classroom.

Once you're done with all of the above, click the "Exit Ticket" button to tell me that you've completed the level.

*Note: If you need/want to download and install R and RStudio on to you computer in the future then you can find instructions [here](https://robwschlegel.github.io/Intro_R_Workshop/prelim.html#using-your-own-computer).*

## Summary of things to do

* Read [this]((https://robwschlegel.github.io/Intro_R_Workshop/prelim.html#why-use-r)
* Sign up for an [RStudio Cloud Account](https://rstudio.cloud/plans/free)
* Get added to my [RStudio Cloud Classroom](linkhere)
* Submit an [Exit Ticket](linkhere)

