---
title: 'Scaling'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: no
quiz: https://rstudio.cloud/spaces/170089/project/2982675
---

The final way to edit your plots (and maybe the hardest) is changing the scales. In ggplot, scales are functions that determine how aesthetics are mapped to your plot. They are used to change how far along the x-axis your points are plotted, or determine which colors/shapes/sizes are used to display certain variables. We've already a couple of examples of scales when we looked at zooming and switching the direction of our y-axis for vertical profile plots. However, the most likely change you're going to want to make is what colors are used to color the lines/points that represent your variables.

## Scales Primer

To learn more about scales and how to use them, go through the "Scales" section of [this primer](https://rstudio.cloud/learn/primers/3.8). It will introduce you to some common methods for changing a color scale in your plot.

## Exercise

Try some of this yourself in the RStudio Cloud exercise below.
