---
title: Discussions
author: Ben Harden
date: '2021-05-20'
slug: []
categories: []
tags: []
draft: no
---

## Overview

For some L3 work, we will be doing some small group discussions. These are intended to give you a space to demonstrate what you know and probe a series of questions as a small group. 

These conversations will be modeled after the Socratic Seminar method where students lead and direct the discussion without input from an instructor. You will be given material to read and questions to look at ahead of time - the conversation should be focused on these questions, but can diverge a little as long as the topic in questions remains the focus of discussion.

The following subsections describe what you will be asked to do.

### Preparation

You will need to read some materials, possibly review some past levels, and gather together your thoughts in response to a series of questions. You should not only focus on things you feel you can explain well, but also prepare to talk about aspects you didn't understand or need additional insight on. If it helps, you should prepare some notes ahead of time to bring with you.

### Discussion

You will be grouped with your peers and given a set period of time in which to discuss the topic. The goal of these discussions is to share understanding and embrace different interpretations. Your job as contributor of information is only half your role in the discussion - you also need to ask good questions and help others by synthesizing ideas and asking for clarifications. You should also practice good discussion etiquette. Some things to consider:

* Engage one another rather than simply giving everyone a turn to say their piece.
* Take leadership to continue discussion un-aided by instructors for the full time period.
* Practice summarizing or synthesizing ideas from the group.
* Ask for clarification and respectfully disagree with thoughts as needed
* If necessary, think about questions for the group that extend beyond those initially asked (whilst still staying on topic).
* Try not to just stop what you are saying and wait for someone else to pick it up. Offer a question or ask for another persons thoughts.
* Demonstrate an ability to acknowledge what someone has said and build off it.
* Try and be cognizant of the time you've spent speaking and don't dominate discussion for long stretches.
* Bring others into the conversation by asking helpful, open-ended questions (not putting them on the spot).

## Scoring

Level discussions will be scored 0-10 for final grade contribution. This score will be split equally between your demonstration of understanding and your participation in the discussion.

```{r, echo = FALSE}
knitr::kable(
  tibble::tribble(~"Score", ~"Understanding",~"Participation",
                  "1", "No Contribution","No Contribution",
                  "2", "Offered limited foundational ideas","Contributed in limited manner",
                  "3", "Demonstrated application of Level 1 and 2 ideas","Offered thoughts and asked questions",
                  "4", "Analysis in relation to Level 3 reading","Brought others into conversation through helpful questions",
                  "5"," Detailed analysis and evaluation","Helped guide conversation through synthesis, summaries and clarification questions"))
```