---
title: "Zooming"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, include = TRUE, cache = FALSE, message = FALSE, warning = FALSE)
```

So we've spent some time thinking about the basics of what to plot and how to plot it. You've already had to make some decisions geoms and mapping, but now we're going to see some of the other things that R can do to customize your plots and make them publication ready.

## Zooming

One of the first things you might want to do with your plot is to zoom in on a specific region. Even if your final figure will be zoomed-out, this can be a needed tool in exploring your data.

You should work your way through the "Zooming" section of [this primer](https://rstudio.cloud/learn/primers/3.8) for information on two ways to achieve this. 

## Exercise

Once you feel comfortable with these ideas, head over to the RStudio Cloud assignment below to apply this to one of the datasets we've already been working with.
