---
title: 'Reflection'
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 4
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/MzQ0NzAxMjMwNDU0/a/NDEyODQ1OTg5NzYx/details
---

You've done a complicated thing in producing your climate story by combining good writing for voice, effective environmental communication, and storytelling elements.

You should now reflect on this process by submitting at least one page (12pt, double-spaced), but no more than two pages that seeks to answer the following questions:

* What did you think of your final story? What were some of the strong aspects and what do you think could have been improved?

* What were some of the enjoyable and challenging aspects of writing and preforming a radio story?

* How would you change/improve this story given more time and access to possible interview subjects? What other voices would have been good to hear from?

* What did you learn about yourself as a communicator through undertaking this project and how would this change your approach to doing another communication project?