---
title: 'Better Climate Stories'
author: Ben Harden
date: "`r format(Sys.time(), '%Y-%m-%d')`"
level: 3
slug: []
categories: []
tags: []
draft: no
---

So, what is our best course of action for telling stories about the environment and climate change?
We are going to synthesize what we have been thinking about in the Communicate topic into a small-group discussion

## Reading

Before we get to the climate change communication discussion. I'd like to introduce one more piece of literature. 

You should read [this article](rgifford_33_dragons_new_scientist.pdf), which summarizes psychologist Robert Gifford's work on the internal mechanisms by which we make decisions and take action with regards to climate change. He calls them the "Dragons of Climate Change Inaction". The full article is [here](2011 Climate Change in AP Dragons.pdf) if you are interested in more details.

You should take some notes on the dragons that resonated with you the most and which you may have personal experience or experience of others actions to support.

## Exercise

We will be having a small-group discussion on this topic in order to try and answer the question:

> What are the most effective ways to communicate about the environment and climate change that are likely to encourage the most action?

You should prepare for this discussion by reviewing the readings in the Communication topic so far including:

- Effective communication strategies on climate change
- Storytelling theory
- Stories we've talked about in class
- The above reading on psychological barriers

You should synthesize these into a personal argument about ways you feel are most effective in eliciting action. You should be prepared to state some opinions, but back them up with some facts based on the readings. You should also seek to combine your ideas with others to build a broader consensus.